default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: laki  
  password: laki
  host: localhost

development:
  <<: *default
  database: friends_app_development

test:
  <<: *default
  database: friends_app_test

production:
  <<: *default
  database: friends_app_production
  username: laki
  password: <%= ENV['FRIENDS_APP_DATABASE_PASSWORD'] %>
  host: localhost
